name: flutter_oss_licenses
description: A new Flutter project.
version: 1.0.1
publish_to: none
homepage: https://github.com/espresso3389/flutter_oss_licenses

environment:
  sdk: ">=2.12.0 <3.0.0"

executables:
  generate:

dependencies:
  path: ^1.8.0
  meta: ^1.7.0
  yaml: ^3.1.0
  dart_oss_licenses:
    path: ../dart_oss_licenses

dev_dependencies:
  flutter_lints: ^1.0.4
